karten = [
    {
        "name": "Black Widow",
        "beschreibung": "Spionin mit Präzision, Taser und Tarnung.",
        "bild": "https://i.imgur.com/0u0GRC9.png",
        "seltenheit": "Gewöhnlich",
        "hp": 150,
        "attacks": [
            {"name": "Treten", "damage": [10, 15], "info": "Stabiler Nahkampfangriff."},
            {"name": "Taser", "damage": [5, 25], "info": "Riskanter Angriff mit hohem Maximalschaden."},
            {
                "name": "Präzisionsschuss",
                "damage": [20, 35],
                "requires_reload": True,
                "reload_name": "Nachladen",
                "info": "Starker Schuss. Danach ist erst Nachladen nötig.",
            },
            {
                "name": "Tarnung",
                "damage": [0, 0],
                "cooldown_turns": 2,
                "effects": [{"type": "delayed_defense_after_next_attack", "target": "self", "defense": "stealth", "chance": 1.0}],
                "info": "Schutz wird vorbereitet und ist nach deinem nächsten Angriff für den darauffolgenden Gegnerzug aktiv.",
            },
        ],
    },
    {
        "name": "Iron-Man",
        "beschreibung": "Hightech-Avenger im gepanzerten Kampfanzug.",
        "bild": "https://i.imgur.com/HxcQOw5.png",
        "seltenheit": "Gewöhnlich",
        "hp": 160,
        "attacks": [
            {"name": "Repulsor Strahlen", "damage": [5, 20], "info": "Standardstrahl mit breiter Schadensspanne."},
            {
                "name": "Überladung",
                "damage": [0, 0],
                "self_damage": 5,
                "cooldown_turns": 2,
                "effects": [{"type": "damage_multiplier", "target": "self", "multiplier": 1.65, "uses": 1}],
                "info": "Nächster Angriff macht +65%, verursacht 5 Selbstschaden und hat 1 Runde Abklingzeit.",
            },
            {"name": "Unibeamstrahl", "damage": [25, 30], "cooldown_turns": 3, "info": "Starker Energiestrahl mit 3 Runden Cooldown."},
            {
                "name": "Fliegen",
                "damage": [0, 0],
                "cooldown_turns": 3,
                "effects": [{"type": "airborne_two_phase", "target": "self", "landing_damage": [20, 40], "chance": 1.0}],
                "info": "Phase 1: hebt ab und weicht dem nächsten Angriff aus. Phase 2: automatischer Landungsschlag (20-40).",
            },
        ],
    },
    {
        "name": "Captain America",
        "beschreibung": "Der erste Avenger mit Schild und Taktik.",
        "bild": "https://i.imgur.com/T1pX1QU.png",
        "seltenheit": "Gewöhnlich",
        "hp": 165,
        "attacks": [
            {"name": "Schildwurf", "damage": [10, 20], "info": "Solider Distanzangriff mit dem Schild."},
            {"name": "Inspiration", "damage": [0, 0], "heal": 20, "cooldown_turns": 4, "info": "Heilt sofort 20 HP."},
            {
                "name": "Schild-Block",
                "damage": [0, 0],
                "effects": [{"type": "damage_reduction_sequence", "target": "self", "sequence": [0.4, 0.6]}],
                "info": "Blockt den nächsten Treffer um 40%, danach den darauffolgenden um 60%.",
            },
            {"name": "Hieb", "damage": [15, 25], "info": "Direkter Nahkampfhieb."},
        ],
    },
    {
        "name": "Hulk",
        "beschreibung": "Rohe Kraft, Gamma-Wut und pure Zerstörung.",
        "bild": "https://i.imgur.com/PcbEJOS.png",
        "seltenheit": "Gewöhnlich",
        "hp": 190,
        "attacks": [
            {"name": "Smash", "damage": [5, 20], "info": "Unberechenbarer Wuchtangriff."},
            {
                "name": "Gammastrahl",
                "damage": [0, 0],
                "effects": [{"type": "burning", "chance": 1.0, "duration": [2, 7], "damage": 5}],
                "info": "Verursacht keinen Direktschaden, aber Brennen für 2-7 Runden (5 pro Tick).",
            },
            {
                "name": "Unverwundbarkeit",
                "damage": [0, 0],
                "effects": [{"type": "damage_boost", "target": "self", "amount": 5, "uses": 2}],
                "info": "Nächste 2 Angriffe verursachen jeweils +5 Schaden.",
            },
            {"name": "Sprung", "damage": [10, 40], "info": "Sprungangriff mit sehr hoher Streuung."},
        ],
    },
    {
        "name": "Hawkeye",
        "beschreibung": "Präziser Fernkämpfer mit Spezialpfeilen.",
        "bild": "https://i.imgur.com/tpRd9by.png",
        "seltenheit": "Gewöhnlich",
        "hp": 145,
        "attacks": [
            {
                "name": "Flammen Pfeil",
                "damage": [5, 5],
                "cooldown_turns": 3,
                "effects": [{"type": "burning", "chance": 1.0, "duration": [3, 3], "damage": 5}],
                "info": "Macht sofort 5 Schaden und setzt den Gegner 3 Runden in Brand (5 pro Tick).",
            },
            {"name": "Pfeil", "damage": [5, 15], "info": "Standardpfeil."},
            {
                "name": "Treffsicherheit",
                "damage": [0, 0],
                "cooldown_turns": 5,
                "effects": [{"type": "guaranteed_hit", "target": "self", "uses": 1}],
                "info": "Der nächste Angriff trifft garantiert.",
            },
            {
                "name": "Triple Arrow",
                "damage": [0, 30],
                "multi_hit": {"hits": 3, "hit_chance": 0.45, "per_hit_damage": [1, 10]},
                "info": "3 Pfeile mit je 45% Trefferchance; jeder Treffer macht 1-10 Schaden.",
            },
        ],
    },
    {
        "name": "Doctor Strange",
        "beschreibung": "Meister der mystischen Künste.",
        "bild": "https://i.imgur.com/4mxNv2c.png",
        "seltenheit": "Gewöhnlich",
        "hp": 155,
        "attacks": [
            {"name": "Eldritch-Peitsche", "damage": [10, 18], "info": "Mystischer Peitschenangriff."},
            {
                "name": "Auge von Agamotto",
                "damage": [0, 0],
                "cooldown_turns": 4,
                "effects": [{"type": "stun", "target": "enemy", "chance": 1.0}],
                "info": "Der Gegner setzt seine nächste Runde aus.",
            },
            {
                "name": "Spiegeldimension",
                "damage": [0, 0],
                "cooldown_turns": 3,
                "effects": [{"type": "reflect", "target": "self", "reduce_percent": 0.5, "reflect_ratio": 1.0, "chance": 1.0}],
                "info": "Nächster Treffer wird halbiert; die verhinderte Hälfte wird zurückgeworfen.",
            },
            {"name": "Strahlen der Vishanti", "damage": [0, 40], "info": "Sehr instabiler Zauber mit hohem Potenzial."},
        ],
    },
    {
        "name": "Black Panther",
        "beschreibung": "Königlicher Krieger mit Vibranium-Power.",
        "bild": "https://i.imgur.com/4mxNv2c.png",
        "seltenheit": "Gewöhnlich",
        "hp": 165,
        "attacks": [
            {"name": "Vibranium-Krallen", "damage": [12, 18], "info": "Schneller Krallenangriff."},
            {
                "name": "Kinetische Absorption",
                "damage": [0, 0],
                "cooldown_turns": 3,
                "effects": [{"type": "absorb_store", "target": "self", "percent": 0.5, "chance": 1.0}],
                "info": "Reduziert den nächsten Treffer um 50% und speichert den verhinderten Schaden.",
            },
            {"name": "Kinetische Entladung", "damage": [10, 10], "add_absorbed_damage": True, "info": "10 Grundschaden plus gespeicherter Absorptionsschaden."},
            {
                "name": "Jagdinstinkt",
                "damage": [20, 20],
                "cooldown_turns": 4,
                "conditional_enemy_hp_below_pct": 0.5,
                "damage_if_condition": [30, 30],
                "guaranteed_hit_if_condition": True,
                "info": "Macht 20 Schaden; unter 50% Gegner-HP trifft er garantiert für 30.",
            },
        ],
    },
    {
        "name": "Star Lord",
        "beschreibung": "Galaktischer Draufgänger mit Jet-Boots.",
        "bild": "https://i.imgur.com/4mxNv2c.png",
        "seltenheit": "Gewöhnlich",
        "hp": 150,
        "attacks": [
            {"name": "Element-Blaster", "damage": [12, 18], "info": "Zuverlässiger Blasterangriff."},
            {
                "name": "Schwerkraft-Mine",
                "damage": [10, 20],
                "cooldown_turns": 2,
                "effects": [{"type": "enemy_next_attack_reduction_flat", "target": "enemy", "amount": 10, "turns": 1, "chance": 1.0}],
                "info": "Nächster gegnerischer Angriff macht 10 weniger Schaden (mit Überlauf-Rückstoß).",
            },
            {
                "name": "Jet-Boots",
                "damage": [0, 0],
                "cooldown_turns": 3,
                "effects": [
                    {"type": "delayed_defense_after_next_attack", "target": "self", "defense": "evade", "chance": 1.0},
                    {"type": "damage_boost", "target": "self", "amount": 10, "uses": 1, "chance": 1.0},
                ],
                "info": "Gibt dem nächsten eigenen Angriff +10; nach diesem Angriff weicht Star-Lord dem darauffolgenden Gegnerangriff aus.",
            },
            {
                "name": "Awesome Mix",
                "damage": [0, 0],
                "cooldown_turns": 4,
                "effects": [{"type": "mix_heal_or_max", "target": "self", "heal": 15, "chance": 1.0}],
                "info": "50/50: heilt 15 oder der nächste Angriff verursacht Maximalschaden.",
            },
        ],
    },
    {
        "name": "Groot",
        "beschreibung": "Massiver Baumkrieger mit starker Regeneration.",
        "bild": "https://i.imgur.com/4mxNv2c.png",
        "seltenheit": "Gewöhnlich",
        "hp": 180,
        "attacks": [
            {"name": "Rankenschlag", "damage": [10, 18], "info": "Schlag mit schweren Ranken."},
            {
                "name": "Verwurzeln",
                "damage": [5, 15],
                "cooldown_turns": 3,
                "effects": [{"type": "enemy_next_attack_reduction_percent", "target": "enemy", "percent": 0.5, "turns": 1, "chance": 1.0}],
                "info": "Nächster gegnerischer Angriff verursacht 50% weniger Schaden.",
            },
            {"name": "Wachstumsschub", "damage": [0, 0], "heal": [15, 30], "cooldown_turns": 4, "info": "Regeneriert 15-30 HP."},
            {"name": "ICH BIN GROOT!", "damage": [25, 40], "cooldown_turns": 5, "info": "Massiver Schwerangriff."},
        ],
    },
    {
        "name": "Rocket",
        "beschreibung": "Kleiner Genius mit großen Waffen.",
        "bild": "https://i.imgur.com/4mxNv2c.png",
        "seltenheit": "Gewöhnlich",
        "hp": 135,
        "attacks": [
            {"name": "Duale Blaster", "damage": [12, 22], "info": "Schneller Doppelbeschuss."},
            {
                "name": "Elektroschock-Falle",
                "damage": [10, 10],
                "cooldown_turns": 3,
                "effects": [{"type": "special_lock", "target": "enemy", "chance": 1.0}],
                "info": "Gegner darf in der nächsten Runde nur den Standardangriff nutzen.",
            },
            {
                "name": "Das dicke Ding",
                "damage": [40, 55],
                "self_damage": 10,
                "cooldown_turns": 5,
                "info": "Extrem starker Schuss, aber 10 Rückstoßschaden.",
            },
            {
                "name": "Kleines Ziel",
                "damage": [0, 0],
                "cooldown_turns": 3,
                "effects": [{"type": "cap_damage", "target": "self", "max_damage": 5, "chance": 1.0}],
                "info": "Der nächste eingehende Treffer wird auf maximal 5 begrenzt.",
            },
        ],
    },
    {
        "name": "Moon Knight",
        "beschreibung": "Avatar von Khonshu mit chaotischem Stil.",
        "bild": "https://i.imgur.com/4mxNv2c.png",
        "seltenheit": "Gewöhnlich",
        "hp": 150,
        "attacks": [
            {"name": "Mondsicheln", "damage": [12, 18], "info": "Präziser Sichelwurf."},
            {"name": "Chaos-Stil", "damage": [5, 30], "cooldown_turns": 2, "info": "Chaotischer Angriff mit großer Streuung."},
            {"name": "Segen des Khonshu", "damage": [0, 0], "heal": [15, 25], "cooldown_turns": 4, "info": "Heilt 15-25 HP."},
            {
                "name": "Rache des Avatars",
                "damage": [20, 20],
                "bonus_if_self_hp_below_pct": 0.5,
                "bonus_damage_if_condition": 10,
                "cooldown_turns": 5,
                "info": "Macht 20 Schaden, unter 50% eigener HP macht er 30.",
            },
        ],
    },
    {
        "name": "Blade",
        "beschreibung": "Daywalker mit Katana und Jagdinstinkt.",
        "bild": "https://i.imgur.com/4mxNv2c.png",
        "seltenheit": "Gewöhnlich",
        "hp": 155,
        "attacks": [
            {"name": "Silber-Katana", "damage": [12, 18], "info": "Schneller Katana-Angriff."},
            {"name": "Daywalker-Biss", "damage": [15, 20], "lifesteal_ratio": 0.5, "cooldown_turns": 3, "info": "Heilt 50% des verursachten Schadens."},
            {
                "name": "UV-Granate",
                "damage": [10, 15],
                "cooldown_turns": 3,
                "effects": [{"type": "blind", "target": "enemy", "miss_chance": 0.5, "chance": 1.0}],
                "info": "Nächster gegnerischer Angriff hat 50% Verfehlchance.",
            },
            {
                "name": "Jagdfieber",
                "damage": [25, 35],
                "cooldown_turns": 5,
                "effects": [{"type": "burning", "chance": 1.0, "duration": [2, 2], "damage": 5}],
                "info": "Starker Angriff plus Blutung/Brennen für 2 Runden (5 pro Tick).",
            },
        ],
    },
    {
        "name": "Wolverine",
        "beschreibung": "Unaufhaltsam mit Heilfaktor und Adamantium.",
        "bild": "https://i.imgur.com/4mxNv2c.png",
        "seltenheit": "Gewöhnlich",
        "hp": 170,
        "attacks": [
            {"name": "Adamantium-Krallen", "damage": [12, 18], "info": "Brutaler Krallenhieb."},
            {
                "name": "Heilfaktor",
                "damage": [0, 0],
                "cooldown_turns": 3,
                "effects": [{"type": "regen", "target": "self", "turns": 3, "heal": 10, "chance": 1.0}],
                "info": "Heilt 3 Runden lang je 10 HP.",
            },
            {
                "name": "Berserkerwut",
                "damage": [20, 30],
                "cooldown_turns": 3,
                "bonus_if_self_hp_below_pct": 0.5,
                "bonus_damage_if_condition": 10,
                "info": "Macht 20-30, unter 50% eigener HP zusätzlich +10.",
            },
            {
                "name": "X-Schnitt",
                "damage": [15, 20],
                "cooldown_turns": 4,
                "effects": [{"type": "burning", "chance": 1.0, "duration": [3, 3], "damage": 5}],
                "info": "Verursacht tiefe Wunde für 3 Runden (5 pro Tick).",
            },
        ],
    },
    {
        "name": "Spider-Man",
        "beschreibung": "Schneller Netzkämpfer mit Spinnensinn.",
        "bild": "https://i.imgur.com/4mxNv2c.png",
        "seltenheit": "Gewöhnlich",
        "hp": 145,
        "attacks": [
            {"name": "Netzschuss", "damage": [10, 15], "info": "Schneller Netztreffer."},
            {
                "name": "Spinnensinn",
                "damage": [0, 0],
                "cooldown_turns": 3,
                "effects": [{"type": "evade", "target": "self", "counter": 10, "chance": 1.0}],
                "info": "Weicht dem nächsten Angriff aus und kontert mit 10 Schaden.",
            },
            {
                "name": "Netz-Versiegelung",
                "damage": [5, 5],
                "cooldown_turns": 3,
                "effects": [{"type": "enemy_next_attack_reduction_flat", "target": "enemy", "amount": 15, "turns": 1, "chance": 1.0}],
                "info": "Nächster gegnerischer Angriff macht 15 weniger Schaden (mit Überlauf-Rückstoß).",
            },
            {"name": "Netzschwing-Combo", "damage": [20, 35], "cooldown_turns": 4, "info": "Dynamische Kombo mit hohem Schaden."},
        ],
    },
]
