COMMON = "Gewöhnlich"
RARE = "Selten"
DEFAULT_HP = 140
NEW_CARD_IMAGE = "https://i.imgur.com/4mxNv2c.png"

# Zentraler Konfig-Block für spätere Balance-Anpassungen.
DIRECT_DAMAGE_CAP = 999  # Maximales Schadenslimit für direkten normalen Angriffsschaden.
STANDARD_DAMAGE_UPGRADE_STEP = 4  # So viel Schaden bekommt ein Standardangriff pro Upgrade dazu.
STANDARD_DAMAGE_UPGRADE_MAX_TIMES = 2  # So oft darf ein Standardangriff maximal verbessert werden.
SPECIAL_DAMAGE_UPGRADE_STEP = 3  # So viel Schaden bekommt eine Spezialfähigkeit pro Upgrade dazu.
SPECIAL_DAMAGE_UPGRADE_MAX_TIMES = 5  # So oft darf eine Spezialfähigkeit maximal verbessert werden.
DOT_TYPE_DEFAULTS = {
    "burning": {"label": "Brand", "icon": "🔥", "max_damage": 999},  # Standardwerte für Brand-Schaden über Zeit.
    "poison": {"label": "Gift", "icon": "☠️", "max_damage": 999},  # Standardwerte für Gift-Schaden über Zeit.
    "bleeding": {"label": "Blutung", "icon": "🩸", "max_damage": 999},  # Standardwerte für Blutungs-Schaden über Zeit.
}


karten = [
    {
        "name": "Black Widow",
        "beschreibung": "Spionin mit Präzision, Taser und Tarnung.",
        "bild": "https://i.imgur.com/0u0GRC9.png",
        "seltenheit": COMMON,
        "hp": DEFAULT_HP,
        "attacks": [
            {"name": "Treten", "damage": [10, 15], "info": "Stabiler Nahkampfangriff."},
            {"name": "Taser", "damage": [10, 25], "cooldown_turns": 3, "info": "Riskanter Taserangriff mit 2 Runden Abklingzeit im Design."},
            {
                "name": "Präzisionsschuss",
                "damage": [20, 35],
                "requires_reload": True,
                "reload_name": "Nachladen",
                "info": "Starker Schuss. Danach muss zuerst nachgeladen werden.",
            },
            {
                "name": "Tarnung",
                "damage": [0, 0],
                "cooldown_turns": 5,
                "effects": [{"type": "delayed_defense_after_next_attack", "target": "self", "defense": "stealth", "chance": 1.0}],
                "info": "Bereitet Tarnung vor. Nach dem nächsten eigenen Angriff wird der darauffolgende Gegnerangriff geblockt.",
            },
        ],
    },
    {
        "name": "Iron-Man",
        "beschreibung": "Tony Stark im Anzug, bereit für den Kampf.",
        "bild": "https://i.imgur.com/HxcQOw5.png",
        "seltenheit": COMMON,
        "variants": [
            {
                "variant_id": "Standard_Iron-Man",
                "display_name": "Standard_Iron-Man",
                "image_url": "https://i.imgur.com/HxcQOw5.png",
                "admin_only": False,
                "reward_enabled": True,
                "sort_order": 0,
                "is_default": True,
            },
            {
                "variant_id": "Alpha_Iron-Man",
                "display_name": "Alpha_Iron-Man",
                "image_url": "https://i.imgur.com/ge54AbX.png",
                "admin_only": True,
                "reward_enabled": False,
                "sort_order": 1,
            },
        ],
        "hp": DEFAULT_HP,
        "attacks": [
            {"name": "Repulsor Strahlen", "damage": [5, 20], "info": "Standardstrahl mit breiter Schadensspanne."},
            {
                "name": "Überladung",
                "damage": [0, 0],
                "self_damage": 5,
                "cooldown_turns": 3,
                "effects": [{"type": "damage_multiplier", "target": "self", "multiplier": 1.5, "uses": 1}],
                "info": "Der nächste Angriff macht +50% Schaden, verursacht aber 5 Selbstschaden.",
            },
            {"name": "Unibeamstrahl", "damage": [25, 30], "cooldown_turns": 5, "info": "Starker Energiestrahl mit hoher Abklingzeit."},
            {
                "name": "Fliegen",
                "damage": [0, 0],
                "cooldown_turns": 5,
                "effects": [{"type": "airborne_two_phase", "target": "self", "landing_damage": [20, 40], "chance": 1.0}],
                "info": "Weicht dem nächsten Angriff aus und landet danach automatisch mit 20-40 Schaden.",
            },
        ],
    },
    {
        "name": "Captain America",
        "beschreibung": "Der erste Avenger mit Schild und Taktik.",
        "bild": "https://i.imgur.com/T1pX1QU.png",
        "seltenheit": COMMON,
        "hp": DEFAULT_HP,
        "attacks": [
            {
                "name": "Schildwurf",
                "damage": [15, 20],
                "requires_reload": True,
                "reload_name": "Aufsammeln",
                "info": "Wirft das Schild. Danach muss es zuerst wieder aufgesammelt werden.",
            },
            {"name": "Inspiration", "damage": [0, 0], "heal": 25, "cooldown_turns": 5, "info": "Heilt sofort 25 HP."},
            {
                "name": "Schild-Block",
                "damage": [0, 0],
                "cooldown_turns": 5,
                "effects": [{"type": "damage_reduction_sequence", "target": "self", "sequence": [0.6, 0.3]}],
                "info": "Reduziert den nächsten Treffer um 60% und den darauffolgenden um 30%.",
            },
            {"name": "Hieb", "damage": [5, 25], "info": "Direkter Nahkampfhieb."},
        ],
    },
    {
        "name": "Hulk",
        "beschreibung": "Rohe Kraft, Gamma-Wut und pure Zerstörung.",
        "bild": "https://i.imgur.com/PcbEJOS.png",
        "seltenheit": COMMON,
        "hp": DEFAULT_HP,
        "attacks": [
            {"name": "Smash", "damage": [18, 24], "info": "Schwerer Schlag mit viel Wucht."},
            {
                "name": "Gammastrahl",
                "damage": [0, 0],
                "effects": [{"type": "burning", "chance": 1.0, "duration": [2, 7], "damage": 5}],
                "info": "Verursacht Brennen für 2-7 Runden mit 5 Schaden pro Runde.",
            },
            {
                "name": "Gamma-Wut",
                "damage": [0, 0],
                "cooldown_turns": 4,
                "effects": [{"type": "damage_boost", "target": "self", "amount": 10, "uses": 2}],
                "info": "Die nächsten 2 Angriffe verursachen jeweils +10 Schaden.",
            },
            {"name": "Sprung", "damage": [25, 40], "cooldown_turns": 5, "info": "Brutaler Sprungangriff mit hoher Schadensspanne."},
        ],
    },
    {
        "name": "Hawkeye",
        "beschreibung": "Präziser Fernkämpfer mit Spezialpfeilen.",
        "bild": "https://i.imgur.com/tpRd9by.png",
        "seltenheit": COMMON,
        "hp": DEFAULT_HP,
        "attacks": [
            {
                "name": "Flammen Pfeil",
                "damage": [10, 10],
                "cooldown_turns": 5,
                "damage_breakdown": {"start_damage": 10, "burn_damage_per_round": 5, "burn_duration_rounds": 3},
                "effects": [{"type": "burning", "chance": 1.0, "duration": [3, 3], "damage": 5}],
                "info": "Startschaden 10 plus Brennen: 3 Runden x 5 Schaden.",
            },
            {"name": "Pfeil", "damage": [12, 18], "is_standard_attack": True, "info": "Standardpfeil."},
            {
                "name": "Treffsicherheit",
                "damage": [0, 0],
                "cooldown_turns": 5,
                "effects": [{"type": "guaranteed_hit", "target": "self", "uses": 1}, {"type": "force_max", "target": "self", "uses": 1}],
                "info": "Der nächste Angriff trifft garantiert und verursacht Maximalschaden.",
            },
            {
                "name": "Triple Arrow",
                "damage": [0, 0],
                "cooldown_turns": 4,
                "multi_hit": {"hits": 3, "hit_chance": 1.0, "per_hit_damage": [5, 10], "guaranteed_min_per_hit": 5},
                "info": "3 Pfeile treffen nacheinander und verursachen jeweils 5-10 Schaden.",
            },
        ],
    },
    {
        "name": "Doctor Strange",
        "beschreibung": "Meister der mystischen Künste.",
        "bild": "https://i.imgur.com/DRM6CsN.png",
        "seltenheit": COMMON,
        "hp": DEFAULT_HP,
        "attacks": [
            {"name": "Eldritch-Peitsche", "damage": [10, 18], "info": "Mystischer Peitschenangriff."},
            {
                "name": "Auge von Agamotto",
                "damage": [0, 0],
                "cooldown_turns": 5,
                "button_style": "success",
                "effects": [{"type": "stun", "target": "enemy", "chance": 1.0}],
                "info": "Der Gegner setzt seinen nächsten Zug aus.",
            },
            {
                "name": "Spiegeldimension",
                "damage": [0, 0],
                "cooldown_turns": 5,
                "button_style": "primary",
                "effects": [{"type": "reflect", "target": "self", "reduce_percent": 0.5, "reflect_ratio": 1.0, "chance": 1.0}],
                "info": "Der nächste Treffer wird halbiert und der verhinderte Schaden wird komplett zurückgeworfen.",
            },
            {"name": "Strahlen der Vishanti", "damage": [10, 45], "cooldown_turns": 5, "info": "Instabiler, aber sehr starker Zauber."},
        ],
    },
    {
        "name": "Black Panther",
        "beschreibung": "Königlicher Krieger mit Vibranium-Power.",
        "bild": "https://i.imgur.com/Ts6cdlR.png",
        "seltenheit": COMMON,
        "hp": DEFAULT_HP,
        "attacks": [
            {"name": "Vibranium-Krallen", "damage": [12, 18], "info": "Schneller Krallenangriff."},
            {
                "name": "Kinetische Absorption",
                "damage": [0, 0],
                "cooldown_turns": 4,
                "effects": [{"type": "absorb_store", "target": "self", "percent": 0.5, "chance": 1.0}],
                "info": "Reduziert den nächsten Treffer um 50% und speichert den verhinderten Schaden.",
            },
            {
                "name": "Kinetische Entladung",
                "damage": [10, 10],
                "add_absorbed_damage": True,
                "cooldown_turns": 4,
                "info": "Verursacht 10 Grundschaden plus gespeicherten Absorptionsschaden.",
            },
            {
                "name": "Jagdinstinkt",
                "damage": [20, 20],
                "cooldown_turns": 5,
                "conditional_enemy_hp_below_pct": 0.5,
                "damage_if_condition": [30, 30],
                "guaranteed_hit_if_condition": True,
                "info": "Verursacht 20 Schaden. Unter 50% Gegner-HP trifft er garantiert für 30.",
            },
        ],
    },
    {
        "name": "Star Lord",
        "beschreibung": "Galaktischer Draufgänger mit Jet-Boots.",
        "bild": "https://i.imgur.com/wPKMwOl.png",
        "seltenheit": COMMON,
        "hp": DEFAULT_HP,
        "attacks": [
            {"name": "Element-Blaster", "damage": [15, 18], "info": "Zuverlässiger Blasterangriff."},
            {
                "name": "Schwerkraft-Mine",
                "damage": [15, 15],
                "cooldown_turns": 4,
                "effects": [{"type": "enemy_next_attack_reduction_flat", "target": "enemy", "amount": 10, "turns": 1, "chance": 1.0}],
                "info": "Verursacht 15 Schaden. Der nächste gegnerische Angriff macht 10 Schaden weniger.",
            },
            {
                "name": "Jet-Boots",
                "damage": [0, 0],
                "cooldown_turns": 5,
                "effects": [
                    {"type": "delayed_defense_after_next_attack", "target": "self", "defense": "evade", "chance": 1.0},
                    {"type": "damage_boost", "target": "self", "amount": 10, "uses": 1, "chance": 1.0},
                ],
                "info": "Der nächste eigene Angriff verursacht +10 Schaden. Danach wird dem folgenden Gegnerangriff ausgewichen.",
            },
            {
                "name": "Awesome Mix",
                "damage": [0, 0],
                "cooldown_turns": 6,
                "effects": [{"type": "mix_heal_or_max", "target": "self", "heal": 20, "chance": 1.0}],
                "info": "50/50: heilt 20 HP oder der nächste Angriff verursacht Maximalschaden.",
            },
        ],
    },
    {
        "name": "Groot",
        "beschreibung": "Ich bin Groot mit starker Regeneration.",
        "bild": "https://i.imgur.com/YhjJ7KV.png",
        "seltenheit": COMMON,
        "hp": DEFAULT_HP,
        "attacks": [
            {"name": "Rankenschlag", "damage": [15, 20], "info": "Schlag mit schweren Ranken."},
            {
                "name": "Verwurzeln",
                "damage": [5, 15],
                "cooldown_turns": 4,
                "effects": [{"type": "enemy_next_attack_reduction_percent", "target": "enemy", "percent": 0.5, "turns": 1, "chance": 1.0}],
                "info": "Der nächste gegnerische Angriff verursacht 50% weniger Schaden.",
            },
            {"name": "Wachstumsschub", "damage": [0, 0], "heal": [15, 30], "cooldown_turns": 6, "info": "Regeneriert 15-30 HP."},
            {"name": "ICH BIN GROOT!", "damage": [35, 45], "cooldown_turns": 6, "info": "Massiver Schwerangriff."},
        ],
    },
    {
        "name": "Rocket",
        "beschreibung": "Kleiner Genius mit großen Waffen.",
        "bild": "https://i.imgur.com/aDQ9RmP.png",
        "seltenheit": COMMON,
        "hp": DEFAULT_HP,
        "attacks": [
            {"name": "Duale Blaster", "damage": [12, 22], "info": "Schneller Doppelbeschuss."},
            {
                "name": "Elektroschock-Falle",
                "damage": [10, 10],
                "cooldown_turns": 5,
                "effects": [{"type": "special_lock", "target": "enemy", "chance": 1.0, "turns": 1}],
                "info": "Verursacht 10 Schaden. Der Gegner darf in der nächsten Runde keine Spezialfähigkeiten nutzen.",
            },
            {
                "name": "Das dicke Ding",
                "damage": [40, 50],
                "self_damage": 15,
                "cooldown_turns": 6,
                "info": "Sehr starker Schuss mit 15 Rückstoßschaden.",
            },
            {
                "name": "Kleines Ziel",
                "damage": [0, 0],
                "cooldown_turns": 4,
                "effects": [{"type": "cap_damage", "target": "self", "max_damage": "attack_min", "chance": 1.0}],
                "info": "Der nächste eingehende Treffer wird auf seinen Mindestschaden begrenzt.",
            },
        ],
    },
    {
        "name": "Moon Knight",
        "beschreibung": "Avatar von Khonshu mit chaotischem Kampfstil.",
        "bild": "https://i.imgur.com/pYzJYPw.png",
        "seltenheit": COMMON,
        "hp": DEFAULT_HP,
        "attacks": [
            {"name": "Mondsicheln", "damage": [12, 18], "info": "Präziser Sichelwurf."},
            {"name": "Chaos-Stil", "damage": [5, 30], "cooldown_turns": 3, "info": "Chaotischer Angriff mit großer Streuung."},
            {"name": "Segen des Khonshu", "damage": [0, 0], "heal": [15, 25], "cooldown_turns": 5, "info": "Heilt 15-25 HP."},
            {
                "name": "Rache des Avatars",
                "damage": [20, 20],
                "bonus_if_self_hp_below_pct": 0.5,
                "bonus_damage_if_condition": 10,
                "cooldown_turns": 5,
                "info": "Verursacht 20 Schaden. Unter 50% eigener HP verursacht der Angriff 30 Schaden.",
            },
        ],
    },
    {
        "name": "Blade",
        "beschreibung": "Daywalker mit Katana und Jagdinstinkt.",
        "bild": "https://i.imgur.com/QN0NwDb.png",
        "seltenheit": COMMON,
        "hp": DEFAULT_HP,
        "attacks": [
            {"name": "Silber-Katana", "damage": [12, 18], "info": "Schneller Katana-Angriff."},
            {
                "name": "Daywalker-Biss",
                "damage": [10, 20],
                "lifesteal_ratio": 0.5,
                "cooldown_turns": 4,
                "info": "Verursacht 10-20 Schaden und heilt 50% des verursachten Schadens.",
            },
            {
                "name": "UV-Granate",
                "damage": [10, 15],
                "cooldown_turns": 4,
                "effects": [{"type": "blind", "target": "enemy", "miss_chance": 0.5, "chance": 1.0}],
                "info": "Der nächste gegnerische Angriff hat 50% Verfehlchance.",
            },
            {
                "name": "Jagdfieber",
                "damage": [25, 35],
                "cooldown_turns": 6,
                "effects": [{"type": "burning", "chance": 1.0, "duration": [2, 2], "damage": 5}],
                "info": "Starker Angriff plus Blutung/Brennen für 2 Runden mit 5 Schaden.",
            },
        ],
    },
    {
        "name": "Wolverine",
        "beschreibung": "Unaufhaltsam mit Heilfaktor und Adamantium.",
        "bild": "https://i.imgur.com/vpyHxDi.png",
        "seltenheit": COMMON,
        "hp": DEFAULT_HP,
        "attacks": [
            {"name": "Adamantium-Krallen", "damage": [12, 18], "info": "Brutaler Krallenhieb."},
            {
                "name": "Heilfaktor",
                "damage": [0, 0],
                "cooldown_turns": 7,
                "effects": [{"type": "regen", "target": "self", "turns": 3, "heal": 10, "chance": 1.0}],
                "info": "Heilt sich in den nächsten 3 Runden jeweils um 10 HP.",
            },
            {
                "name": "Berserkerwut",
                "damage": [20, 30],
                "cooldown_turns": 4,
                "bonus_if_self_hp_below_pct": 0.5,
                "bonus_damage_if_condition": 10,
                "info": "Verursacht 20-30 Schaden. Unter 50% eigener HP gibt es +10 extra.",
            },
            {
                "name": "X-Schnitt",
                "damage": [15, 20],
                "cooldown_turns": 5,
                "effects": [{"type": "burning", "chance": 1.0, "duration": [3, 3], "damage": 5}],
                "info": "Tiefe Wunde für 3 Runden mit 5 Schaden.",
            },
        ],
    },
    {
        "name": "Spider-Man",
        "beschreibung": "Schneller Netzkämpfer mit Spinnensinn.",
        "bild": "https://i.imgur.com/ivYMZ7H.png",
        "seltenheit": COMMON,
        "hp": DEFAULT_HP,
        "attacks": [
            {"name": "Netzschuss", "damage": [10, 15], "info": "Schneller Netztreffer."},
            {
                "name": "Spinnensinn",
                "damage": [0, 0],
                "cooldown_turns": 5,
                "effects": [{"type": "evade", "target": "self", "counter": 15, "chance": 1.0}],
                "info": "Weicht dem nächsten Angriff aus und kontert mit 15 Schaden.",
            },
            {
                "name": "Netz-Versiegelung",
                "damage": [0, 0],
                "cooldown_turns": 5,
                "effects": [{"type": "enemy_next_attack_reduction_flat", "target": "enemy", "amount": 15, "turns": 1, "chance": 1.0}],
                "info": "Der nächste gegnerische Angriff verursacht 15 Schaden weniger.",
            },
            {"name": "Netzschwing-Combo", "damage": [25, 35], "cooldown_turns": 5, "info": "Dynamische Kombo mit hohem Schaden."},
        ],
    },
    {
        "name": "Venom",
        "beschreibung": "Brutaler Symbiont mit Biss, Schild und Regeneration.",
        "bild": NEW_CARD_IMAGE,
        "seltenheit": COMMON,
        "hp": DEFAULT_HP,
        "attacks": [
            {"name": "Symbionten-Peitsche", "damage": [10, 15], "info": "Schneller Symbiontenhieb."},
            {
                "name": "Wir sind Venom",
                "damage": [15, 15],
                "heal": 15,
                "heal_chance": 0.45,
                "cooldown_turns": 4,
                "info": "Verursacht 15 Schaden. Mit 45% Wahrscheinlichkeit heilt Venom sich um 15 HP.",
            },
            {
                "name": "Symbionten-Schild",
                "damage": [0, 0],
                "cooldown_turns": 5,
                "effects": [{"type": "reflect", "target": "self", "reduce_percent": 1.0, "reflect_ratio": 0.0, "flat": 10, "chance": 1.0}],
                "info": "Blockt den nächsten Angriff komplett und verursacht 10 Rückstoßschaden.",
            },
            {"name": "Tödlicher Biss", "damage": [30, 45], "cooldown_turns": 6, "info": "Brutaler Biss mit sehr hohem Schaden."},
        ],
    },
    {
        "name": "Captain Marvel",
        "beschreibung": "Kosmische Kämpferin mit Energieaufnahme und Flug.",
        "bild": NEW_CARD_IMAGE,
        "seltenheit": COMMON,
        "hp": DEFAULT_HP,
        "attacks": [
            {"name": "Photonen-Strahl", "damage": [15, 20], "info": "Energiebeschuss mit solider Schadensspanne."},
            {
                "name": "Energie-Absorber",
                "damage": [0, 0],
                "cooldown_turns": 4,
                "effects": [{"type": "absorb_store", "target": "self", "percent": 0.5, "max_store": 20, "chance": 1.0}],
                "info": "Reduziert den nächsten Treffer um 50% und speichert bis zu 20 verhinderten Schaden.",
            },
            {
                "name": "Binär-Schlag",
                "damage": [20, 20],
                "add_absorbed_damage": True,
                "cooldown_turns": 5,
                "cooldown_overrides_by_final_damage": [{"threshold": 27, "turns": 6}],
                "info": "Verursacht 20 Schaden. Nach Energie-Absorber kommt die gespeicherte Ladung dazu.",
            },
            {
                "name": "Sternenflug",
                "damage": [0, 0],
                "cooldown_turns": 7,
                "effects": [
                    {
                        "type": "airborne_two_phase",
                        "target": "self",
                        "landing_damage": [20, 20],
                        "landing_attack": {
                            "name": "Sternenflug-Einschlag",
                            "damage": [20, 20],
                            "effects": [{"type": "stun", "target": "enemy", "chance": 1.0}],
                            "info": "Automatischer Einschlag mit Betäubung.",
                        },
                        "chance": 1.0,
                    }
                ],
                "info": "Weicht dem nächsten Angriff aus und schlägt danach mit 20 Schaden ein. Der Gegner wird betäubt.",
            },
        ],
    },
    {
        "name": "Ms Marvel",
        "beschreibung": "Kamala Khan mit elastischen Spezialfähigkeiten.",
        "bild": NEW_CARD_IMAGE,
        "seltenheit": COMMON,
        "hp": DEFAULT_HP,
        "attacks": [
            {"name": "Dehn-Schlag", "damage": [10, 15], "info": "Elastischer Standardangriff."},
            {"name": "Riesen-Faust", "damage": [20, 30], "cooldown_turns": 4, "info": "Schwere Faust mit hoher Wucht."},
            {
                "name": "Gummiband-Ausweichen",
                "damage": [0, 0],
                "heal": 15,
                "heal_chance": 0.5,
                "cooldown_turns": 5,
                "effects": [{"type": "evade", "target": "self", "counter": 0, "chance": 1.0}],
                "info": "Weicht dem nächsten Angriff aus. Mit 50% Wahrscheinlichkeit heilt Kamala sich um 15 HP.",
            },
            {
                "name": "Wirbelsturm-Kick",
                "damage": [15, 15],
                "cooldown_turns": 5,
                "effects": [{"type": "standard_lock", "target": "enemy", "turns": 1, "chance": 1.0}],
                "info": "Verursacht 15 Schaden und sperrt den nächsten gegnerischen Standardangriff.",
            },
        ],
    },
    {
        "name": "Ant-Man",
        "beschreibung": "Scott Lang mit Schrumpfen, Giant-Man und Pym-Partikeln.",
        "bild": NEW_CARD_IMAGE,
        "seltenheit": COMMON,
        "hp": DEFAULT_HP,
        "attacks": [
            {"name": "Ameisen-Hieb", "damage": [10, 15], "info": "Schneller Treffer im Kleinformat."},
            {
                "name": "Schrumpfen",
                "damage": [0, 0],
                "cooldown_turns": 5,
                "effects": [{"type": "damage_reduction", "target": "self", "percent": 0.5, "turns": 2, "chance": 1.0}],
                "outgoing_damage_penalty": {"amount": 5, "turns": 2},
                "info": "Ant-Man erleidet 2 Runden lang 50% weniger Schaden, verursacht aber selbst 5 Schaden weniger pro Angriff.",
            },
            {
                "name": "Giant-Man",
                "damage": [35, 45],
                "cooldown_turns": 6,
                "next_attack_damage_override": 0,
                "info": "Gewaltiger Angriff. Danach ist Ant-Man erschöpft und der nächste Angriff soll 0 Schaden machen.",
            },
            {
                "name": "Pym-Partikel-Wurf",
                "damage": [15, 15],
                "cooldown_turns": 4,
                "effects": [{"type": "incoming_damage_bonus", "target": "enemy", "amount": 5, "turns": 2, "chance": 1.0}],
                "info": "Verursacht 15 Schaden und macht den Gegner 2 Runden lang anfälliger für Schaden.",
            },
        ],
    },
    {
        "name": "Miles Morales",
        "beschreibung": "Junger Spider-Man mit Tarnung und Venom-Energie.",
        "bild": NEW_CARD_IMAGE,
        "seltenheit": COMMON,
        "hp": DEFAULT_HP,
        "attacks": [
            {"name": "Netz-Schwinger", "damage": [10, 15], "info": "Schneller Netzangriff."},
            {
                "name": "Venom Blast",
                "damage": [15, 20],
                "cooldown_turns": 4,
                "effects": [{"type": "enemy_attack_self_damage", "target": "enemy", "amount": 5, "turns": 1, "chance": 1.0}],
                "info": "Verursacht 15-20 Schaden. Der Gegner soll beim nächsten Angriff 5 Selbstschaden erhalten.",
            },
            {
                "name": "Camouflage",
                "damage": [0, 0],
                "cooldown_turns": 5,
                "effects": [{"type": "evade", "target": "self", "counter": 0, "chance": 1.0}],
                "info": "Miles wird unsichtbar und erleidet beim nächsten gegnerischen Angriff 0 Schaden.",
            },
            {
                "name": "Mega Venom Blast",
                "damage": [35, 45],
                "cooldown_turns": 6,
                "effects": [{"type": "special_lock", "target": "self", "turns": 2, "chance": 1.0}],
                "info": "Gewaltige Explosion. Danach sind Miles' Spezialangriffe 2 Runden lang gesperrt.",
            },
        ],
    },
    {
        "name": "Namor",
        "beschreibung": "Herrscher der Meere mit Dreizack und Flug.",
        "bild": NEW_CARD_IMAGE,
        "seltenheit": COMMON,
        "hp": DEFAULT_HP,
        "attacks": [
            {"name": "Dreizack-Stich", "damage": [12, 18], "info": "Präziser Nahkampfstich."},
            {
                "name": "Ruf des Ozeans",
                "damage": [10, 10],
                "cooldown_turns": 4,
                "effects": [{"type": "status_immunity", "target": "self", "turns": 1, "chance": 1.0}],
                "info": "Verursacht 10 Schaden und macht Namor für die nächste gegnerische Runde immun gegen negative Zustände.",
            },
            {
                "name": "Flug der Knöchelflügel",
                "damage": [0, 0],
                "cooldown_turns": 4,
                "effects": [
                    {
                        "type": "airborne_two_phase",
                        "target": "self",
                        "landing_damage": [20, 20],
                        "landing_attack": {"name": "Luftsturz", "damage": [20, 20], "info": "Automatischer Sturzangriff aus der Luft."},
                        "chance": 1.0,
                    }
                ],
                "info": "Weicht dem nächsten Angriff aus und stößt danach mit 20 Schaden aus der Luft herab.",
            },
            {
                "name": "Zorn des Imperator Rex",
                "damage": [30, 45],
                "cooldown_turns": 6,
                "bonus_if_self_hp_below_pct": 0.35,
                "bonus_damage_if_condition": 10,
                "info": "Verursacht 30-45 Schaden. Unter 35% HP gibt es +10 extra.",
            },
        ],
    },
    {
        "name": "Nick Fury",
        "beschreibung": "Taktiker mit Verstärkung, Luftschlag und Geheimakten.",
        "bild": NEW_CARD_IMAGE,
        "seltenheit": COMMON,
        "hp": DEFAULT_HP,
        "attacks": [
            {"name": "S.H.I.E.L.D. Dienstwaffe", "damage": [10, 15], "info": "Solider Standardschuss."},
            {"name": "Luftschlag angefordert", "damage": [20, 30], "cooldown_turns": 4, "info": "Schwerer Luftschlag."},
            {
                "name": "S.H.I.E.L.D. Verstärkung",
                "damage": [0, 0],
                "cooldown_turns": 5,
                "effects": [
                    {"type": "damage_reduction", "target": "self", "percent": 0.25, "turns": 2, "chance": 1.0},
                    {"type": "damage_boost", "target": "self", "amount": 10, "uses": 2, "chance": 1.0},
                ],
                "info": "Nimmt 2 Runden lang 25% weniger Schaden und verstärkt die nächsten Angriffe um +10.",
            },
            {
                "name": "Geheimakte",
                "damage": [0, 0],
                "cooldown_turns": 6,
                "effects": [{"type": "damage_multiplier", "target": "self", "multiplier": 2.0, "uses": 1, "chance": 1.0}],
                "info": "Der nächste Angriff verursacht doppelten Schaden.",
            },
        ],
    },
    {
        "name": "Shang-Chi",
        "beschreibung": "Meister der Ringe und des Nahkampfs.",
        "bild": NEW_CARD_IMAGE,
        "seltenheit": COMMON,
        "hp": DEFAULT_HP,
        "attacks": [
            {"name": "Präzisionsschlag", "damage": [10, 15], "info": "Schneller und sauberer Treffer."},
            {
                "name": "Ring-Verteidigung",
                "damage": [0, 0],
                "cooldown_turns": 4,
                "effects": [
                    {"type": "damage_reduction", "target": "self", "percent": 0.4, "turns": 1, "chance": 1.0},
                    {"type": "damage_boost", "target": "self", "amount": 10, "uses": 1, "chance": 1.0},
                ],
                "info": "Erleidet 40% weniger Schaden und der nächste Angriff macht +10 Schaden.",
            },
            {
                "name": "Fünf-Finger-Explosion",
                "damage": [15, 25],
                "cooldown_turns": 5,
                "effects": [{"type": "stun", "target": "enemy", "chance": 0.45}],
                "info": "Verursacht 15-25 Schaden. Mit 45% Chance wird der Gegner betäubt.",
            },
            {
                "name": "Zehn-Ringe-Wucht",
                "damage": [0, 0],
                "cooldown_turns": 6,
                "multi_hit": {"hits": 5, "hit_chance": 0.8, "per_hit_damage": [8, 8], "guaranteed_min_per_hit": 8},
                "info": "Bis zu 5 Ringe treffen und verursachen jeweils 8 Schaden.",
            },
        ],
    },
    {
        "name": "She-Hulk",
        "beschreibung": "Juristische Wucht mit Gegenargumenten aus Gamma-Kraft.",
        "bild": NEW_CARD_IMAGE,
        "seltenheit": COMMON,
        "hp": DEFAULT_HP,
        "attacks": [
            {"name": "Juristischer Schlag", "damage": [12, 18], "info": "Klarer Standardtreffer."},
            {
                "name": "Beweisaufnahme",
                "damage": [15, 15],
                "cooldown_turns": 4,
                "effects": [{"type": "disable_enemy_evade_and_block", "target": "enemy", "turns": 1, "chance": 1.0}],
                "info": "Verursacht 15 Schaden und deaktiviert kurzzeitig gegnerisches Ausweichen und Blocken.",
            },
            {
                "name": "Einspruch!",
                "damage": [0, 0],
                "cooldown_turns": 4,
                "effects": [{"type": "reflect", "target": "self", "reduce_percent": 0.5, "reflect_ratio": 0.0, "flat": 10, "chance": 1.0}],
                "info": "Reduziert den nächsten Treffer um 50% und verursacht 10 feste Verfahrenskosten als Rückschaden.",
            },
            {"name": "Schlussplädoyer", "damage": [35, 50], "cooldown_turns": 6, "info": "Schwerer Finisher mit hoher Schadensspanne."},
        ],
    },
    {
        "name": "Sue Storm",
        "beschreibung": "Unsichtbare Kraftfelder und präzise Verteidigung.",
        "bild": NEW_CARD_IMAGE,
        "seltenheit": COMMON,
        "hp": DEFAULT_HP,
        "attacks": [
            {"name": "Kraftfeld-Explosion", "damage": [10, 15], "info": "Direkter Kraftfeldstoß."},
            {
                "name": "Unsichtbarer Schutz",
                "damage": [0, 0],
                "cooldown_turns": 6,
                "effects": [{"type": "shield", "target": "self", "hp": 25, "break_counter": 10, "max_hits": 1, "chance": 1.0}],
                "info": "Absorbiert beim nächsten Angriff bis zu 25 Schaden und verursacht beim Zerbrechen 10 Rückschaden.",
            },
            {
                "name": "Kraftfeld-Infiltration",
                "damage": [20, 20],
                "cooldown_turns": 5,
                "ignore_defense": True,
                "ignore_shield": True,
                "info": "Verursacht 20 Schaden und soll Schilde sowie Verteidigung ignorieren.",
            },
            {
                "name": "Implosions-Kuppel",
                "damage": [25, 25],
                "cooldown_turns": 6,
                "effects": [{"type": "stun", "target": "enemy", "chance": 1.0}],
                "info": "Verursacht 25 Schaden und betäubt den Gegner.",
            },
        ],
    },
    {
        "name": "Thor",
        "beschreibung": "Gott des Donners mit Blitz, Heilung und schwerem Einschlag.",
        "bild": NEW_CARD_IMAGE,
        "seltenheit": COMMON,
        "hp": DEFAULT_HP,
        "attacks": [
            {"name": "Mjölnir-Wurf", "damage": [15, 18], "info": "Klassischer Hammerwurf."},
            {
                "name": "Ruf des Donners",
                "damage": [15, 15],
                "cooldown_turns": 4,
                "effects": [{"type": "enemy_special_self_damage", "target": "enemy", "amount": 10, "turns": 1, "chance": 1.0}],
                "info": "Verursacht 15 Schaden. Die nächste gegnerische Spezialfähigkeit verursacht zusätzlich 10 Selbstschaden.",
            },
            {
                "name": "Gott des Donners",
                "damage": [0, 0],
                "heal": 15,
                "cooldown_turns": 5,
                "effects": [{"type": "damage_boost", "target": "self", "amount": 10, "uses": 1, "chance": 1.0}],
                "info": "Heilt 15 HP und verstärkt den nächsten Angriff um +10 Schaden.",
            },
            {
                "name": "Der Götterschlag",
                "damage": [45, 45],
                "cooldown_turns": 7,
                "cooldown_overrides_by_final_damage": [{"threshold": 55, "turns": 8}],
                "info": "Verursacht 45 Schaden. Mit Verstärkung steigt die Abklingzeit bei sehr hohem Schaden weiter an.",
            },
        ],
    },
    {
        "name": "Mr. Fantastic",
        "beschreibung": "Genialer Taktiker mit elastischer Reflexion.",
        "bild": NEW_CARD_IMAGE,
        "seltenheit": COMMON,
        "hp": DEFAULT_HP,
        "attacks": [
            {"name": "Präzisions-Dehnung", "damage": [10, 15], "info": "Elastischer Präzisionsangriff."},
            {
                "name": "Molekular-Reflektion",
                "damage": [0, 0],
                "cooldown_turns": 4,
                "effects": [{"type": "reflect", "target": "self", "reduce_percent": 0.5, "reflect_ratio": 1.0, "chance": 1.0}],
                "info": "Reduziert den nächsten Treffer um 50% und wirft denselben verhinderten Schaden zurück.",
            },
            {
                "name": "Taktische Analyse",
                "damage": [0, 0],
                "cooldown_turns": 5,
                "effects": [
                    {"type": "blind", "target": "enemy", "miss_chance": 0.5, "chance": 1.0},
                    {"type": "damage_boost", "target": "self", "amount": 20, "uses": 1, "chance": 1.0},
                    {"type": "increase_random_enemy_cooldown", "target": "enemy", "amount": 1, "chance": 1.0},
                ],
                "info": "Der nächste gegnerische Angriff hat 50% Verfehlchance und Reeds nächster Angriff macht +20 Schaden.",
            },
            {
                "name": "Hyper-Intelligenz-Schlag",
                "damage": [30, 30],
                "cooldown_turns": 6,
                "cooldown_overrides_by_final_damage": [{"threshold": 40, "turns": 7}, {"threshold": 55, "turns": 8}],
                "info": "Verursacht 30 Schaden. Nach Taktische Analyse wird der Angriff deutlich stärker.",
            },
        ],
    },
    {
        "name": "The Thing",
        "beschreibung": "Steinharter Brawler mit Schild und schwerem Finisher.",
        "bild": NEW_CARD_IMAGE,
        "seltenheit": COMMON,
        "hp": DEFAULT_HP,
        "attacks": [
            {"name": "Steinharte Faust", "damage": [12, 18], "info": "Schwerer Standardhieb."},
            {
                "name": "Es ist Zeit zum Klopfen!",
                "damage": [15, 15],
                "cooldown_turns": 5,
                "effects": [{"type": "enemy_next_attack_reduction_percent", "target": "enemy", "percent": 0.5, "turns": 1, "chance": 1.0}],
                "info": "Verursacht 15 Schaden und halbiert den nächsten gegnerischen Angriff.",
            },
            {
                "name": "Felsenhaut",
                "damage": [0, 0],
                "cooldown_turns": 6,
                "effects": [{"type": "shield", "target": "self", "hp": 40, "stun_immunity": True, "chance": 1.0}],
                "info": "Verleiht ein Schild mit 40 HP und schützt solange vor Betäubung.",
            },
            {
                "name": "Clobberin' Time",
                "damage": [40, 55],
                "cooldown_turns": 7,
                "heal_if_self_hp_below_pct": 0.3,
                "heal_if_condition": 20,
                "info": "Verursacht 40-55 Schaden. Unter 30% HP heilt Ben sich danach um 20 HP.",
            },
        ],
    },
    {
        "name": "Human Torch",
        "beschreibung": "Feuer, Brand und explosive Hitze.",
        "bild": NEW_CARD_IMAGE,
        "seltenheit": COMMON,
        "hp": DEFAULT_HP,
        "attacks": [
            {
                "name": "Feuerball",
                "damage": [12, 12],
                "effects": [{"type": "burning", "target": "enemy", "duration": [1, 1], "damage": 5, "chance": 1.0}],
                "info": "Verursacht 12 Schaden plus 5 Brandschaden in der nächsten Runde.",
            },
            {
                "name": "Flammenwand",
                "damage": [0, 0],
                "cooldown_turns": 5,
                "effects": [{"type": "interrupt_enemy_standard_or_heal_self", "target": "enemy", "damage": 15, "heal": 10, "turns": 1, "chance": 1.0}],
                "info": "Die nächste gegnerische Aktion wird abgefangen: Standardangriff wird unterbrochen oder Human Torch heilt sich.",
            },
            {
                "name": "Supernova-Ladung",
                "damage": [0, 0],
                "cooldown_turns": 4,
                "effects": [{"type": "burn_multiplier", "target": "self", "multiplier": 2.0, "uses": 1, "chance": 1.0}],
                "info": "Verdoppelt den Brandschaden des nächsten eigenen Brand-Effekts.",
            },
            {
                "name": "FLAMME AN!",
                "damage": [30, 30],
                "cooldown_turns": 6,
                "effects": [{"type": "burning", "target": "enemy", "duration": [2, 2], "damage": 5, "chance": 1.0}],
                "info": "Verursacht sofort 30 Schaden plus 2 Runden lang 5 Brandschaden.",
            },
        ],
    },
    {
        "name": "Cyclops",
        "beschreibung": "Taktischer Strahlnutzer mit Fokus und Finisher.",
        "bild": NEW_CARD_IMAGE,
        "seltenheit": COMMON,
        "hp": DEFAULT_HP,
        "attacks": [
            {"name": "Optischer Strahl", "damage": [10, 15], "info": "Präziser Standardstrahl."},
            {
                "name": "Taktisches Manöver",
                "damage": [0, 0],
                "cooldown_turns": 5,
                "effects": [
                    {"type": "evade", "target": "self", "counter": 0, "chance": 1.0},
                    {"type": "incoming_damage_bonus", "target": "enemy", "amount": 5, "turns": 2, "chance": 1.0},
                ],
                "info": "Cyclops weicht dem nächsten Angriff aus und erhöht 2 Runden lang den eingehenden Schaden des Gegners.",
            },
            {
                "name": "Visier-Anpassung",
                "damage": [0, 0],
                "cooldown_turns": 5,
                "effects": [
                    {"type": "damage_boost", "target": "self", "amount": 15, "uses": 1, "chance": 1.0},
                    {"type": "guaranteed_hit", "target": "self", "uses": 1, "chance": 1.0},
                ],
                "info": "Der nächste Angriff verursacht +15 Schaden und kann nicht ausgewichen werden.",
            },
            {"name": "Mega-Optic-Blast", "damage": [40, 50], "cooldown_turns": 7, "info": "Massiver Finisher mit hoher Wucht."},
        ],
    },
]


karten.extend(
    [
        {
            "name": "Loki",
            "beschreibung": "Täuschung, Ausweichen und gestohlene Kräfte.",
            "bild": NEW_CARD_IMAGE,
            "seltenheit": RARE,
            "hp": DEFAULT_HP,
            "attacks": [
                {"name": "Täuschungs-Dolch", "damage": [12, 16], "info": "Schneller Standardangriff."},
                {
                    "name": "Illusion",
                    "damage": [0, 0],
                    "cooldown_turns": 5,
                    "effects": [
                        {"type": "evade", "target": "self", "counter": 0, "chance": 1.0},
                        {"type": "increase_last_enemy_special_cooldown", "target": "enemy", "amount": 1, "chance": 1.0},
                    ],
                    "info": "Weicht dem nächsten Angriff aus. Falls möglich, wird die zuletzt benutzte gegnerische Spezialfähigkeit um 1 Runde verlängert.",
                },
                {
                    "name": "Gedankenkontrolle",
                    "damage": [15, 15],
                    "cooldown_turns": 6,
                    "effects": [{"type": "copy_last_enemy_special", "target": "enemy", "fallback_damage": 15, "chance": 1.0}],
                    "info": "Kopiert die zuletzt benutzte gegnerische Spezialfähigkeit. Falls nichts kopierbar ist, macht Loki 15 Schaden.",
                },
                {
                    "name": "Zepter-Stoß",
                    "damage": [30, 40],
                    "cooldown_turns": 5,
                    "effects": [{"type": "enemy_next_special_self_damage", "target": "enemy", "amount": 15, "turns": 1, "chance": 1.0}],
                    "info": "Starker Treffer. Die nächste gegnerische Spezialfähigkeit kostet den Gegner 15 HP.",
                },
            ],
        },
        {
            "name": "Ultron",
            "beschreibung": "Drohnen, Anpassung und kalte Optimierung.",
            "bild": NEW_CARD_IMAGE,
            "seltenheit": RARE,
            "hp": DEFAULT_HP,
            "attacks": [
                {"name": "Encephalon-Strahl", "damage": [13, 17], "info": "Präziser Standardstrahl."},
                {
                    "name": "Drohnen-Schwarm",
                    "damage": [0, 0],
                    "cooldown_turns": 5,
                    "effects": [{"type": "bleeding", "target": "enemy", "duration": [3, 3], "damage": 6, "chance": 1.0}],
                    "info": "Drei Runden lang verursachen Drohnen passiv je 6 Schaden.",
                },
                {
                    "name": "Reaktive Evolution",
                    "damage": [0, 0],
                    "cooldown_turns": 6,
                    "effects": [{"type": "reactive_evolution", "target": "self", "amount": 2, "max_stacks": 3, "chance": 1.0}],
                    "info": "Ultron nimmt dauerhaft 2 Schaden weniger vom zuletzt analysierten Angriffstyp.",
                },
                {
                    "name": "System-Optimierung",
                    "damage": [35, 45],
                    "cooldown_turns": 6,
                    "cooldown_overrides_by_final_damage": [{"threshold": 55, "turns": 7}],
                    "heal_if_self_hp_below_pct": 0.5,
                    "heal_if_condition": 15,
                    "info": "Starker Treffer. Unter 50% HP heilt Ultron sich zusätzlich um 15 HP.",
                },
            ],
        },
        {
            "name": "Scarlet Witch",
            "beschreibung": "Chaosmagie mit Fluch und Cooldown-Kontrolle.",
            "bild": NEW_CARD_IMAGE,
            "seltenheit": RARE,
            "hp": DEFAULT_HP,
            "attacks": [
                {"name": "Chaos-Energie", "damage": [11, 19], "info": "Unberechenbarer Standardangriff."},
                {
                    "name": "Wahrscheinlichkeits-Verzerrung",
                    "damage": [0, 0],
                    "cooldown_turns": 4,
                    "effects": [{"type": "enemy_force_min_damage", "target": "enemy", "turns": 1, "chance": 1.0}],
                    "info": "Der nächste gegnerische Angriff verursacht nur seinen Minimalwert.",
                },
                {
                    "name": "Realitäts-Shift",
                    "damage": [0, 0],
                    "cooldown_turns": 7,
                    "effects": [{"type": "reset_own_cooldown", "target": "self", "chance": 1.0}],
                    "info": "Setzt eine bereits genutzte eigene Fähigkeit sofort auf Cooldown 0 zurück.",
                },
                {
                    "name": "Hex-Fluch",
                    "damage": [32, 42],
                    "cooldown_turns": 5,
                    "effects": [{"type": "heal_curse", "target": "enemy", "damage": 15, "turns": 2, "chance": 1.0}],
                    "info": "Starker Chaosangriff. In den nächsten 2 Runden nimmt der Gegner 15 Schaden, wenn er heilen will.",
                },
            ],
        },
        {
            "name": "Deadpool",
            "beschreibung": "Chaos, Selbstschaden und Finisher-Logik.",
            "bild": NEW_CARD_IMAGE,
            "seltenheit": RARE,
            "hp": DEFAULT_HP,
            "attacks": [
                {"name": "Katanas & Knarren", "damage": [13, 18], "info": "Deadpools Standardangriff."},
                {
                    "name": "4. Wand brechen",
                    "damage": [0, 0],
                    "heal": [20, 30],
                    "cooldown_turns": 5,
                    "effects": [{"type": "next_attack_flat_penalty", "target": "self", "amount": 5, "turns": 1, "chance": 1.0}],
                    "info": "Heilt 20-30 HP, aber der nächste eigene Angriff macht 5 Schaden weniger.",
                },
                {
                    "name": "Maximum Effort",
                    "damage": [0, 0],
                    "self_damage": 10,
                    "cooldown_turns": 4,
                    "effects": [{"type": "damage_boost", "target": "self", "amount": 20, "uses": 1, "chance": 1.0}],
                    "info": "Deadpool nimmt 10 Selbstschaden und erhält +20 Schaden auf den nächsten Angriff.",
                },
                {
                    "name": "Hex-Fluch",
                    "damage": [35, 50],
                    "cooldown_turns": 6,
                    "cooldown_overrides_by_final_damage": [{"threshold": 55, "turns": 7}],
                    "effects": [{"type": "finisher_below_hp", "target": "enemy", "threshold": 20, "chance": 1.0}],
                    "info": "Finisher. Bringt der Treffer den Gegner unter 20 HP, wird er sofort besiegt.",
                },
            ],
        },
        {
            "name": "Carnage",
            "beschreibung": "Blutung, Heilung und brutale Finisher.",
            "bild": NEW_CARD_IMAGE,
            "seltenheit": RARE,
            "hp": DEFAULT_HP,
            "attacks": [
                {"name": "Symbionten-Sicheln", "damage": [14, 19], "info": "Carnages Standardangriff."},
                {
                    "name": "Blut-Massaker",
                    "damage": [18, 24],
                    "cooldown_turns": 5,
                    "effects": [
                        {"type": "bleeding", "target": "enemy", "duration": [3, 3], "damage": 6, "chance": 1.0},
                        {"type": "heal_from_target_dot", "target": "enemy", "dot_type": "bleeding", "chance": 1.0},
                    ],
                    "info": "Verursacht Blutung für 3 Runden. Carnage heilt sich um den Blutungsschaden des Gegners.",
                },
                {
                    "name": "Wahnsinniger Ausbruch",
                    "damage": [35, 35],
                    "self_damage": 15,
                    "cooldown_turns": 4,
                    "unblockable": True,
                    "info": "Opfert 15 eigene HP für 35 unblockbaren Schaden.",
                },
                {
                    "name": "Chaos-Sturm",
                    "damage": [40, 50],
                    "cooldown_turns": 6,
                    "cooldown_overrides_by_final_damage": [{"threshold": 55, "turns": 7}],
                    "effects": [{"type": "disable_enemy_heal_if_bleeding", "target": "enemy", "turns": 3, "chance": 1.0}],
                    "info": "Massiver Angriff. Bluten Gegner bereits, ist deren Heilung 3 Runden lang deaktiviert.",
                },
            ],
        },
    ]
)

for card in karten:
    attacks = list(card.get("attacks", []))
    if not attacks:
        continue
    if card.get("name") == "Hawkeye":
        for attack in attacks:
            attack.pop("is_standard_attack", None)
        attacks[0]["is_standard_attack"] = True
        continue
    if not any(bool(attack.get("is_standard_attack")) for attack in attacks[:4]):
        attacks[0]["is_standard_attack"] = True
